Stroke = raceDataMetaNew{1,5};
RaceDist = raceDataMetaNew{1,4};
Course = raceDataMetaNew{1,6};
RaceTime = raceDataMetaNew{1,7};
RaceDate = raceDataMetaNew{1,3};

AthleteGreenEyeId = raceDataMetaNew{1,2};
GreenEyeIDall = AthleteGreenEyeDB(2:end,1);
AMSIDall1 = AthleteAMSDB(2:end,2);
proceed = 1;
iter = 1;

searchCol = cell2mat(GreenEyeIDall);
indexGreenEyeID = find(searchCol == AthleteGreenEyeId);
if isempty(indexGreenEyeID) == 1;
    AthleteGreenEyeFirstname = [];
    AthleteGreenEyeLastname = [];
else;
    AthleteGreenEyeFirstname = AthleteGreenEyeDB{indexGreenEyeID+1,3};
    AthleteGreenEyeLastname = AthleteGreenEyeDB{indexGreenEyeID+1,2};
end;

searchCol = cell2mat(AMSIDall1);
indexAMSID = find(searchCol == AthleteGreenEyeId);
if isempty(AthleteGreenEyeFirstname) == 0;
    if isempty(indexAMSID) == 0;
        indexName = find(contains(lower(AthleteAMSDB(:,7)),lower(AthleteGreenEyeFirstname)) & ...
            contains(lower(AthleteAMSDB(:,8)),lower(AthleteGreenEyeLastname)));
        if isempty(indexName) == 1;
            %Wrong athlete ... equivalent of doesnt exist ... take info from AthleteGreenEyeD
            sourceMeta = 0;
        else;
            %athlete exist ... take info from AthleteAMSDB
            sourceMeta = 1;
        end;
    else;
        indexName = find(contains(lower(AthleteAMSDB(:,7)),lower(AthleteGreenEyeFirstname)) & ...
            contains(lower(AthleteAMSDB(:,8)),lower(AthleteGreenEyeLastname)));
        if isempty(indexName) == 1;
            %athlete doesnt exist  ... take info from AthleteGreenEyeDB
            sourceMeta = 0;
        else;
            %athlete exist  ... take info from AthleteAMSDB
            sourceMeta = 1;
        end;
    end;
else;
    AMSIDall2 = AthleteAMSDB(2:end,1);
    searchCol = cell2mat(AMSIDall2);
    indexName = find(searchCol == AthleteGreenEyeId);
    indexName = indexName + 1;
    sourceMeta = 1;
end;

Athletename = 'UnknownA';
AthletenameFull = 'UnknownA';
Firstname = 'Athlete';
Lastname = 'Unknown';
Gender = 'MALE';
DOB = '01/01/2000';
Country = 'INTER';

if sourceMeta == 1;
    %AthleteAMSDB
    indexAMSID = AthleteAMSDB{indexName, 1};
    AthleteId = indexAMSID;
    Firstname = AthleteAMSDB{indexName, 7};
    Lastname = AthleteAMSDB{indexName, 8};
    Athletename = [Lastname Firstname(1)];
    AthletenameFull = [Firstname ' ' Lastname];
    Gender = AthleteAMSDB{indexName, 6};
    if Gender == 1;
        Gender = 'MALE';
    elseif Gender == 2;
        Gender = 'FEMALE';
    end;
    DOB = AthleteAMSDB{indexName, 5};
    if isempty(DOB) == 1;
        DOB = '01/01/2000';
    end;
    if length(DOB) > 10;
        DOB = DOB(1:10);
    elseif length(DOB) < 10;
        index = strfind(DOB, '/');
        dayDOB = DOB(1:index(1)-1);
        if length(dayDOB) == 1;
            dayDOB = ['0' dayDOB];
        end;
        DOB = [dayDOB DOB(2:end)];
    end;
    Country = AthleteAMSDB{indexName, 4};

    li = find(handles.ParaDB.AMSID == indexAMSID);
    if isempty(li) == 1;
        Paralympic = 'Able';
    else;
        Paralympic = 'Para';
    end;

elseif sourceMeta == 0;
    %AthleteGreenEyeDB
    indexAMSID = [];
    AthleteId = AthleteGreenEyeDB{indexGreenEyeID+1, 1};
    Firstname = AthleteGreenEyeDB{indexGreenEyeID+1, 3};
    Lastname = AthleteGreenEyeDB{indexGreenEyeID+1, 2};
    Athletename = [Lastname Firstname(1)];
    AthletenameFull = [Firstname ' ' Lastname];
    Gender = upper(AthleteGreenEyeDB{indexGreenEyeID+1, 5});
    DOB = AthleteGreenEyeDB{indexGreenEyeID+1, 4};
    if isempty(DOB) == 1;
        DOB = '01/01/2000';
    end;
    if length(DOB) > 10;
        DOB = DOB(1:10);
    elseif length(DOB) < 10;
        index = strfind(DOB, '/');
        dayDOB = DOB(1:index(1)-1);
        if length(dayDOB) == 1;
            dayDOB = ['0' dayDOB];
        end;
        DOB = [dayDOB DOB(2:end)];
    end;
    Country = AthleteGreenEyeDB{indexGreenEyeID+1, 6};
    if isempty(Country) == 1;
        Country = 'INTER';
    end;
    if strcmpi(lower(Country), 'australia');
        Country = 'AUS';
    elseif strcmpi(lower(Country), 'australian');
        Country = 'AUS';
    else;
        Country = 'INTER';
    end;
    Paralympic = 'Able';
end;


%LongCourse
WR.Men.LCM50FS = 20.91;
WR.Men.LCM100FS = 46.86;
WR.Men.LCM200FS = 102.00;
WR.Men.LCM400FS = 220.07;
WR.Men.LCM800FS = 452.12;
WR.Men.LCM1500FS = 871.02;
WR.Men.LCM50BF = 22.27;
WR.Men.LCM100BF = 49.45;
WR.Men.LCM200BF = 110.34;
WR.Men.LCM50BK = 23.71;
WR.Men.LCM100BK = 51.60;
WR.Men.LCM200BK = 111.92;
WR.Men.LCM50BR = 25.95;
WR.Men.LCM100BR = 56.88;
WR.Men.LCM200BR = 125.95;
WR.Men.LCM200IM = 114.00;
WR.Men.LCM400IM = 243.84;
WR.Men.LCM50FS = 20.91;
WR.Men.LCM100FS = 46.86;
WR.Men.LCM200FS = 102.00;
WR.Men.LCM400FS = 220.07;
WR.Men.LCM800FS = 452.12;
WR.Men.LCM1500FS = 871.02;

WR.Women.LCM50FS = 23.67;
WR.Women.LCM100FS = 51.71;
WR.Women.LCM200FS = 112.98;
WR.Women.LCM400FS = 236.08;
WR.Women.LCM800FS = 484.79;
WR.Women.LCM1500FS = 920.48;
WR.Women.LCM50BF = 24.43;
WR.Women.LCM100BF = 55.48;
WR.Women.LCM200BF = 121.81;
WR.Women.LCM50BK = 26.98;
WR.Women.LCM100BK = 57.45;
WR.Women.LCM200BK = 123.14;
WR.Women.LCM50BR = 29.30;
WR.Women.LCM100BR = 64.13;
WR.Women.LCM200BR = 138.95;
WR.Women.LCM200IM = 126.12;
WR.Women.LCM400IM = 265.87;

%ShortCourse
WR.Men.SCM50FS = 20.16;
WR.Men.SCM100FS = 44.84;
WR.Men.SCM200FS = 99.37;
WR.Men.SCM400FS = 212.25;
WR.Men.SCM800FS = 443.42;
WR.Men.SCM1500FS = 846.88;
WR.Men.SCM50BF = 21.75;
WR.Men.SCM100BF = 47.78;
WR.Men.SCM200BF = 106.85;
WR.Men.SCM50BK = 22.11;
WR.Men.SCM100BK = 48.33;
WR.Men.SCM200BK = 105.63;
WR.Men.SCM50BR = 24.95;
WR.Men.SCM100BR = 55.28;
WR.Men.SCM200BR = 120.16;
WR.Men.SCM100IM = 49.28;
WR.Men.SCM200IM = 109.63;
WR.Men.SCM400IM = 234.81;

WR.Women.SCM50FS = 22.93;
WR.Women.SCM100FS = 50.25;
WR.Women.SCM200FS = 110.31;
WR.Women.SCM400FS = 331.30;
WR.Women.SCM800FS = 477.42;
WR.Women.SCM1500FS = 908.24;
WR.Women.SCM50BF = 24.38;
WR.Women.SCM100BF = 54.05;
WR.Women.SCM200BF = 119.61;
WR.Women.SCM50BK = 25.25;
WR.Women.SCM100BK = 54.89;
WR.Women.SCM200BK = 118.94;
WR.Women.SCM50BR = 28.37;
WR.Women.SCM100BR = 62.36;
WR.Women.SCM200BR = 134.57;
WR.Women.SCM100IM = 56.51;
WR.Women.SCM200IM = 121.86;
WR.Women.SCM400IM = 258.94;

if strcmpi(Gender, 'MALE');
    if strcmpi(Stroke, 'Butterfly');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Men.LCM50BF;
            elseif RaceDist == 100;
                WREC = WR.Men.LCM100BF;
            elseif RaceDist == 200;
                WREC = WR.Men.LCM200BF;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Men.SCM50BF;
            elseif RaceDist == 100;
                WREC = WR.Men.SCM100BF;
            elseif RaceDist == 200;
                WREC = WR.Men.SCM200BF;
            end;
        end;
    elseif strcmpi(Stroke, 'Backstroke');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Men.LCM50BK;
            elseif RaceDist == 100;
                WREC = WR.Men.LCM100BK;
            elseif RaceDist == 200;
                WREC = WR.Men.LCM200BK;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Men.SCM50BK;
            elseif RaceDist == 100;
                WREC = WR.Men.SCM100BK;
            elseif RaceDist == 200;
                WREC = WR.Men.SCM200BK;
            end;
        end;
    elseif strcmpi(Stroke, 'Breaststroke');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Men.LCM50BR;
            elseif RaceDist == 100;
                WREC = WR.Men.LCM100BR;
            elseif RaceDist == 200;
                WREC = WR.Men.LCM200BR;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Men.SCM50BR;
            elseif RaceDist == 100;
                WREC = WR.Men.SCM100BR;
            elseif RaceDist == 200;
                WREC = WR.Men.SCM200BR;
            end;
        end;
    elseif strcmpi(Stroke, 'Freestyle');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Men.LCM50FS;
            elseif RaceDist == 100;
                WREC = WR.Men.LCM100FS;
            elseif RaceDist == 200;
                WREC = WR.Men.LCM200FS;
            elseif RaceDist == 400;
                WREC = WR.Men.LCM400FS;
            elseif RaceDist == 800;
                WREC = WR.Men.LCM800FS;
            elseif RaceDist == 1500;
                WREC = WR.Men.LCM1500FS;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Men.SCM50FS;
            elseif RaceDist == 100;
                WREC = WR.Men.SCM100FS;
            elseif RaceDist == 200;
                WREC = WR.Men.SCM200FS;
            elseif RaceDist == 400;
                WREC = WR.Men.SCM400FS;
            elseif RaceDist == 800;
                WREC = WR.Men.SCM800FS;
            elseif RaceDist == 1500;
                WREC = WR.Men.SCM1500FS;
            end;
        end;
    else;
        if strcmpi(Course, 'LCM');
            if RaceDist == 200;
                WREC = WR.Men.LCM200IM;
            elseif RaceDist == 400;
                WREC = WR.Men.LCM400IM;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 100;
                WREC = WR.Men.SCM100IM;
            elseif RaceDist == 200;
                WREC = WR.Men.SCM200IM;
            elseif RaceDist == 400;
                WREC = WR.Men.SCM400IM;
            end;
        end;
    end;

else;
    if strcmpi(Stroke, 'Butterfly');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Women.LCM50BF;
            elseif RaceDist == 100;
                WREC = WR.Women.LCM100BF;
            elseif RaceDist == 200;
                WREC = WR.Women.LCM200BF;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Women.SCM50BF;
            elseif RaceDist == 100;
                WREC = WR.Women.SCM100BF;
            elseif RaceDist == 200;
                WREC = WR.Women.SCM200BF;
            end;
        end;
    elseif strcmpi(Stroke, 'Backstroke');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Women.LCM50BK;
            elseif RaceDist == 100;
                WREC = WR.Women.LCM100BK;
            elseif RaceDist == 200;
                WREC = WR.Women.LCM200BK;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Women.SCM50BK;
            elseif RaceDist == 100;
                WREC = WR.Women.SCM100BK;
            elseif RaceDist == 200;
                WREC = WR.Women.SCM200BK;
            end;
        end;
    elseif strcmpi(Stroke, 'Breaststroke');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Women.LCM50BR;
            elseif RaceDist == 100;
                WREC = WR.Women.LCM100BR;
            elseif RaceDist == 200;
                WREC = WR.Women.LCM200BR;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Women.SCM50BR;
            elseif RaceDist == 100;
                WREC = WR.Women.SCM100BR;
            elseif RaceDist == 200;
                WREC = WR.Women.SCM200BR;
            end;
        end;
    elseif strcmpi(Stroke, 'Freestyle');
        if strcmpi(Course, 'LCM');
            if RaceDist == 50;
                WREC = WR.Women.LCM50FS;
            elseif RaceDist == 100;
                WREC = WR.Women.LCM100FS;
            elseif RaceDist == 200;
                WREC = WR.Women.LCM200FS;
            elseif RaceDist == 400;
                WREC = WR.Women.LCM400FS;
            elseif RaceDist == 800;
                WREC = WR.Women.LCM800FS;
            elseif RaceDist == 1500;
                WREC = WR.Women.LCM1500FS;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 50;
                WREC = WR.Women.SCM50FS;
            elseif RaceDist == 100;
                WREC = WR.Women.SCM100FS;
            elseif RaceDist == 200;
                WREC = WR.Women.SCM200FS;
            elseif RaceDist == 400;
                WREC = WR.Women.SCM400FS;
            elseif RaceDist == 800;
                WREC = WR.Women.SCM800FS;
            elseif RaceDist == 1500;
                WREC = WR.Women.SCM1500FS;
            end;
        end;
    else;
        if strcmpi(Course, 'LCM');
            if RaceDist == 200;
                WREC = WR.Women.LCM200IM;
            elseif RaceDist == 400;
                WREC = WR.Women.LCM400IM;
            end;
        elseif strcmpi(Course, 'SCM');
            if RaceDist == 100;
                WREC = WR.Women.SCM100IM;
            elseif RaceDist == 200;
                WREC = WR.Women.SCM200IM;
            elseif RaceDist == 400;
                WREC = WR.Women.SCM400IM;
            end;
        end;
    end;
end;

FINApoints = roundn(1000.*((WREC./RaceTime).^3),0);



