
index = strfind(Meet, ' ');
if length(index) == 1;
    competitionName = [Meet(1:index-1) Meet(index+1:end)];

elseif length(index) > 1;
    competitionName = [];
    for i = 1:length(index)+1;
        if i == 1;
            competitionName = [competitionName Meet(1 : index(i)-1)];
        elseif i == length(index)+1;
            competitionName = [competitionName Meet(index(i-1)+1 : end)];
        else;
            competitionName = [competitionName Meet(index(i-1)+1 : index(i)-1)];
        end;
    end;
else;
    competitionName = Meet;
end;
competitionName = [competitionName Year];
filenameDBin = ['s3://sparta2-prod/sparta2-data/' Year '/' competitionName '/' UID '.mat'];
filenameDBoutTemp = '';
filenameDBoutDB = '';
if ispc == 1;
    MDIR = getenv('USERPROFILE');
    filenameDBoutDB = [MDIR '\SP2Synchroniser\RaceDB\' Year '\' competitionName '\' UID '.mat'];
    filenameDBoutTemp = [MDIR '\SP2Synchroniser\RaceDB\Temp\' UID '.mat'];
elseif ismac == 1;
    filenameDBoutDB = ['/Applications/SP2Synchroniser/RaceDB/' Year '/' competitionName '/' UID '.mat'];
    filenameDBoutTemp = ['/Applications/SP2Synchroniser/RaceDB/Temp/' UID '.mat'];
end;
if isfile(filenameDBoutDB) == 0;
    command = ['aws s3 cp ' filenameDBin ' ' filenameDBoutTemp];
    [status, out] = system(command);
    
    [connected,timing] = isnetavl;
    if connected == 1;
        load(filenameDBoutTemp);
        eval(['handles.RacesDB.' UID ' = ' UID ';']);
        loadsuccess(raceEC) = 1;
    else;
        if ispc == 1;
            errorwindow = errordlg('File not existing: Connect your computer to the internet', 'Error');
            jFrame = get(handle(errorwindow), 'javaframe');
            jicon = javax.swing.ImageIcon([MDIR '\SP2Synchroniser\SpartaSynchroniser_IconSoftware.png']);
            jFrame.setFigureIcon(jicon);
            clc;
            loadsuccess(raceEC) = 0;
            return;
        end;  
    end;
else;
    load(filenameDBoutDB);
    eval(['handles.RacesDB.' UID ' = ' UID ';']);
    loadsuccess(raceEC) = 1;
end;
