if strcmpi(Gender, 'MALE');
    if strcmpi(StrokeType, 'Butterfly');
        thresBottom = 0.5;
        thresTop = 3.2;
        thresBottomDisp = 1;
        thresTopDisp = 3.2;        
        cutoffFreq = 4;
        orderval = 3;
        
    elseif strcmpi(StrokeType, 'Backstroke');
        thresBottom = 0.5;
        thresTop = 2.8;
        thresBottomDisp = 1;
        thresTopDisp = 2.8;
        cutoffFreq = 4;
        orderval = 2;

    elseif strcmpi(StrokeType, 'Breaststroke');
        thresBottom = 0;
        thresTop = 3.4;
        thresBottomDisp = 0;
        thresTopDisp = 3.4;
        cutoffFreq = 5;
        orderval = 3;

    elseif strcmpi(StrokeType, 'Freestyle');
        if RaceDist <= 200;
            thresBottom = 0.5;
            thresTop = 3;
            thresBottomDisp = 1.2;
            thresTopDisp = 3;
        else;
            thresBottom = 0.5;
            thresTop = 2.5;
            thresBottomDisp = 1;
            thresTopDisp = 2.3;
        end;
        cutoffFreq = 4;
        orderval = 2;
    else;
        if Course == 25;
            if RaceDist == 100;
                try;
                    if lap == 1;
                        thresBottom = 0.5;
                        thresTop = 3.2;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 2;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 3;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
                
            elseif RaceDist == 150;
                try;
                    thresBottom = 0;
                    thresTop = 1.5;
                    cutoffFreq = 4;
                    orderval = 3;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 1.5;    
                
            elseif RaceDist == 200;
                try;
                    if lap == 1 | lap == 2;
                        thresBottom = 0.5;
                        thresTop = 3.2;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 3 | lap == 4;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 5 | lap == 6;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            elseif RaceDist == 400;
                try;
                    if lap == 1 | lap == 2 | lap == 3 | lap == 4;
                        thresBottom = 0.5;
                        thresTop = 3;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 5 | lap == 6 | lap == 7 | lap == 8;
                        thresBottom = 0.5;
                        thresTop = 2.5;
                        thresBottomDisp = 1.2;
                        thresTopDisp = 2.5;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 9 | lap == 10 | lap == 11 | lap == 12;
                        thresBottom = 0;
                        thresTop = 3;
                        thresBottomDisp = 0;
                        thresTopDisp = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        thresBottomDisp = 1;
                        thresTopDisp = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            end;
        else;
            if RaceDist == 200;
                try;
                    if lap == 1;
                        thresBottom = 0.5;
                        thresTop = 3.2;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 2;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 3;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
                
            elseif RaceDist == 150;
                try;
                    thresBottom = 0;
                    thresTop = 1.5;
                    cutoffFreq = 4;
                    orderval = 3;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 1.5;    
                
            elseif RaceDist == 400;
                try;
                    if lap == 1 | lap == 2;
                        thresBottom = 0.5;
                        thresTop = 3;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 3 | lap == 4;
                        thresBottom = 0.5;
                        thresTop = 2.5;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 5 | lap == 6;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            end;
        end;
    end;
else;
    if strcmpi(StrokeType, 'Butterfly');
        thresBottom = 0.5;
        thresTop = 2.8;
        thresBottomDisp = 0.8;
        thresTopDisp = 2.8;
        cutoffFreq = 4;
        orderval = 3;
    elseif strcmpi(StrokeType, 'Backstroke');
        thresBottom = 0.5;
        thresTop = 2.4;
        thresBottomDisp = 0.8;
        thresTopDisp = 2.4;
        cutoffFreq = 4;
        orderval = 2;
    elseif strcmpi(StrokeType, 'Breaststroke');
        thresBottom = 0;
        thresTop = 2.6;
        thresBottomDisp = 0;
        thresTopDisp = 2.6;
        cutoffFreq = 5;
        orderval = 3;
    elseif strcmpi(StrokeType, 'Freestyle');
        if RaceDist <= 200;
            thresBottom = 0.5;
            thresTop = 2.8;
            thresBottomDisp = 1.2;
            thresTopDisp = 2.8;
        else;
            thresBottom = 0.5;
            thresTop = 2.2;
            thresBottomDisp = 1;
            thresTopDisp = 2.2;
        end;
        cutoffFreq = 4;
        orderval = 2;
    else;
        if Course == 25;
            if RaceDist == 100;
                try;
                    if lap == 1;
                        thresBottom = 0.5;
                        thresTop = 3.2;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 2;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 3;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            elseif RaceDist == 200;
                try;
                    if lap == 1 | lap == 2;
                        thresBottom = 0.5;
                        thresTop = 3.2;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 3 | lap == 4;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 5 | lap == 6;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            elseif RaceDist == 400;
                try;
                    if lap == 1 | lap == 2 | lap == 3 | lap == 4;
                        thresBottom = 0.5;
                        thresTop = 3;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 5 | lap == 6 | lap == 7 | lap == 8;
                        thresBottom = 0.5;
                        thresTop = 2.5;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 9 | lap == 10 | lap == 11 | lap == 12;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            end;
        else;
            if RaceDist == 200;
                try;
                    if lap == 1;
                        thresBottom = 0.5;
                        thresTop = 3.2;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 2;
                        thresBottom = 0.5;
                        thresTop = 2.8;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 3;
                        thresBottom = 0;
                        thresTop = 3;
                        cutoffFreq = 5;
                        orderval = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            elseif RaceDist == 400;
                try;
                    if lap == 1 | lap == 2;
                        thresBottom = 0.5;
                        thresTop = 3;
                        cutoffFreq = 4;
                        orderval = 3;
                    elseif lap == 3 | lap == 4;
                        thresBottom = 0.5;
                        thresTop = 2.5;
                        cutoffFreq = 4;
                        orderval = 2;
                    elseif lap == 5 | lap == 6;
                        thresBottom = 0;
                        thresTop = 3;
                    else;
                        thresBottom = 0.5;
                        thresTop = 2.3;
                        cutoffFreq = 4;
                        orderval = 2;
                    end;
                end;
                thresBottomDisp = 0;
                thresTopDisp = 3;
            end;
        end;
    end;
end;